[package]
name = "hell-o"
version = "0.1.0"
edition = "2021"


[dependencies]
axum = {version = "0.8.8", features = ["json"]}
tokio = { version = "1.48.0", features = ["full"] }
serde_json = "1.0.80"
http-body-util = "0.1.0"


[dev-dependencies]
tower = {version = "0.5.0", features = ["util"]}
